#Exercise 1: finding no of points outside N_Dim unit sphere(i.e. area of unit square - area of one fourth circle embeded inside unit square )

In [11]:
import numpy as np

In [12]:
ndim=3
npoints=1000000

In [13]:
#method 1:
%%time
points = np.random.rand(npoints,ndim)
dist_from_origin=np.zeros((npoints,1))
for i in range(npoints):
  for j in range(ndim):
    dist_from_origin[i] +=points[i,j]**2
count =0
for i in range(npoints):
  if dist_from_origin[i]>1 :
    count+=1
fraction_of_points_out_of_circle=count/npoints
print("are of area outside n dim unit sphere is: ",fraction_of_points_out_of_circle)

are of area outside n dim unit sphere is:  0.476091
CPU times: user 11.9 s, sys: 45.2 ms, total: 11.9 s
Wall time: 12 s


In [14]:
#method 2:
%%time
points = np.random.rand(npoints,ndim)
points=np.square(points)
points=np.sum(points,axis = 1)# if axis is 1 then it does addition along the axis of column
fraction_of_points_out_of_circle=np.sum(points >1)/npoints
print("are of area outside n dim unit sphere is: ",fraction_of_points_out_of_circle)

are of area outside n dim unit sphere is:  0.476285
CPU times: user 60.1 ms, sys: 4.78 ms, total: 64.9 ms
Wall time: 65.3 ms


In [15]:
#method 2 single line notation:
%%time
points = np.random.rand(npoints,ndim)
fraction_of_points_out_of_circle=np.sum(np.sum(np.square(points),axis = 1)>1)/npoints
print("are of area outside n dim unit sphere is: ",fraction_of_points_out_of_circle)

are of area outside n dim unit sphere is:  0.476677
CPU times: user 56.3 ms, sys: 2.18 ms, total: 58.5 ms
Wall time: 59.7 ms


In [18]:
##method 2 single line function build:
def area_outside_sphere(npoints,ndim):
  points = np.random.rand(npoints,ndim)
  dist_from_origin=np.zeros((npoints,1))
  return np.sum(np.sum(np.square(points),axis = 1)>1)/npoints

for i in range(2,11):
  print(f'area out side sphere in {i} dimensions is : {area_outside_sphere(10**7,i)}')


area out side sphere in 2 dimensions is : 0.2144644
area out side sphere in 3 dimensions is : 0.4760545
area out side sphere in 4 dimensions is : 0.6915355
area out side sphere in 5 dimensions is : 0.8356848
area out side sphere in 6 dimensions is : 0.9192907
area out side sphere in 7 dimensions is : 0.9632182
area out side sphere in 8 dimensions is : 0.9841576
area out side sphere in 9 dimensions is : 0.9935316
area out side sphere in 10 dimensions is : 0.9975274


#Case Study: Cricket

In [19]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216




1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has scored a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean for Sachin's scores based on which quartile India's score falls in
7.   For every match find out who has has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on average after having scored x runs
9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...



In [4]:
#common initialisations:
import numpy as np
cric_data=np.loadtxt("cric_data.tsv",skiprows=1,usecols=(1,2,3))

In [49]:
#1.Find mean, median, IQR for Sachin, Rahul, and India
mean=np.mean(cric_data,axis=0)
median=np.median(cric_data,axis=0)
percentiles=np.percentile(cric_data,[25,75],axis=0)
mean=np.round(mean,2)
iqr=[]
for i in range (3):
  iqr.append([percentiles[1,i]-percentiles[0,i]])
print(f"mean median and iqr of Sachin is : {mean[0]}, {median[0]}, {iqr[0][0]} respectively")
print(f"mean median and iqr of Rahul is : {mean[1]}, {median[1]}, {iqr[1][0]} respectively")
print(f"mean median and iqr of India is : {mean[2]}, {median[2]}, {iqr[2][0]} respectively")

mean median and iqr of Sachin is : 39.88, 27.0, 57.0 respectively
mean median and iqr of Rahul is : 32.06, 22.0, 46.0 respectively
mean median and iqr of India is : 220.8, 216.0, 98.0 respectively


In [32]:
#2.Find the histogram of Sachin's scores with 10 bins
sachin_data=cric_data[:,0]
np.histogram(sachin_data,bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [34]:
#3.Find mean of Sachin's scores for each groupe of 25 matches
np.mean(sachin_data.reshape(9,25),axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [70]:
#4.Find mean of Sachin's scores where he has scored a century
np.mean(sachin_data[sachin_data>=100])

125.0

In [109]:
#5.Find mean of Sachin's scores when Rahul has scored less than 10
np.mean(cric_data[cric_data[:,1]<10][:,0]).round(2)

40.74

In [53]:
#6.Find mean for Sachin's scores based on which quartile India's score falls in.(solution 1)
india_quartiles=np.percentile(cric_data[:,2],[25,50,75,100],axis=0)
india=cric_data[:,2]
for i in range(len(india_quartiles)):
  print(f"mean of sachin score in india's quartile {i+1} is\
  {np.mean(cric_data[india<=india_quartiles[i]][:,0]).round(2)} ")

mean of sachin score in india's quartile 1 is  20.91 
mean of sachin score in india's quartile 2 is  27.93 
mean of sachin score in india's quartile 3 is  32.09 
mean of sachin score in india's quartile 4 is  39.88 


In [54]:
#6.(v2)Find mean for Sachin's scores based on which quartile India's score falls in.(solution 2)
india_quartiles=np.percentile(cric_data[:,2],[25,50,75,100],axis=0).reshape(4,1)
india=cric_data[:,2]
Indices=india<=india_quartiles
for i in range(4):
  print(f"mean of sachin score in india's quartile {i+1} is\
  {np.mean(sachin_data[Indices[i,:]]).round(2)} ")

mean of sachin score in india's quartile 1 is  20.91 
mean of sachin score in india's quartile 2 is  27.93 
mean of sachin score in india's quartile 3 is  32.09 
mean of sachin score in india's quartile 4 is  39.88 


In [56]:
#7.For every match find out who has has scored more - Sachin or Rahul
is_sachin_higher=cric_data[:,0]>cric_data[:,1]
print(f"Match_No   High_Scorer")
for i in range(len(is_sachin_higher)):
  if is_sachin_higher[i]:
    print(f"{i+1}           Sachin")
  else:
    print(f"{i+1}           Rahul")

Match_No   High_Scorer
1           Sachin
2           Rahul
3           Rahul
4           Sachin
5           Sachin
6           Rahul
7           Rahul
8           Sachin
9           Rahul
10           Sachin
11           Rahul
12           Rahul
13           Rahul
14           Sachin
15           Sachin
16           Rahul
17           Rahul
18           Rahul
19           Rahul
20           Rahul
21           Sachin
22           Rahul
23           Sachin
24           Sachin
25           Rahul
26           Sachin
27           Sachin
28           Rahul
29           Sachin
30           Sachin
31           Sachin
32           Sachin
33           Rahul
34           Rahul
35           Sachin
36           Rahul
37           Rahul
38           Sachin
39           Rahul
40           Sachin
41           Sachin
42           Sachin
43           Sachin
44           Rahul
45           Sachin
46           Rahul
47           Rahul
48           Sachin
49           Rahul
50           Sachin
51         

In [55]:
#7.For every match find out who has has scored more - Sachin or Rahul
# (version 2: using "where" function)
is_sachin_higher=cric_data[:,0]>cric_data[:,1]
np.where(is_sachin_higher,"sachin","Rahul")

array(['sachin', 'Rahul', 'Rahul', 'sachin', 'sachin', 'Rahul', 'Rahul',
       'sachin', 'Rahul', 'sachin', 'Rahul', 'Rahul', 'Rahul', 'sachin',
       'sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'sachin',
       'Rahul', 'sachin', 'sachin', 'Rahul', 'sachin', 'sachin', 'Rahul',
       'sachin', 'sachin', 'sachin', 'sachin', 'Rahul', 'Rahul', 'sachin',
       'Rahul', 'Rahul', 'sachin', 'Rahul', 'sachin', 'sachin', 'sachin',
       'sachin', 'Rahul', 'sachin', 'Rahul', 'Rahul', 'sachin', 'Rahul',
       'sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'sachin', 'Rahul',
       'sachin', 'sachin', 'Rahul', 'Rahul', 'Rahul', 'sachin', 'Rahul',
       'sachin', 'sachin', 'sachin', 'sachin', 'Rahul', 'sachin', 'Rahul',
       'Rahul', 'sachin', 'sachin', 'Rahul', 'Rahul', 'sachin', 'Rahul',
       'Rahul', 'sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'sachin', 'sachin', 'sachin', 'Rahul', 'sachin', 'sachin',
       'sachin', 'Rahul', 'sachin', 'sachin', '

In [110]:
#8.How many more runs does Sachin score on average after having scored x runs
x=20
np.mean(sachin_data[sachin_data>=x]).round(2)

66.82

In [104]:
#9.How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...
cum_sum_sachin=np.cumsum(sachin_data)
matches=0
multiple=1
for i in range(len(cum_sum_sachin)):
  matches += 1
  if cum_sum_sachin[i]>=1000*multiple:
    print(f"sachin scored his {1000*multiple} runs in his {matches}th match")
    multiple +=1

sachin scored his 1000 runs in his 30th match
sachin scored his 2000 runs in his 48th match
sachin scored his 3000 runs in his 74th match
sachin scored his 4000 runs in his 99th match
sachin scored his 5000 runs in his 125th match
sachin scored his 6000 runs in his 151th match
sachin scored his 7000 runs in his 174th match
sachin scored his 8000 runs in his 196th match


In [63]:
#9.How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...
#version 2: using histogram
cum_sum_sachin=np.cumsum(sachin_data)
np.cumsum(np.histogram(cum_sum_sachin,bins=np.arange(0,max(cum_sum_sachin)+1,1000))[0])+1

array([ 30,  48,  74,  99, 125, 151, 174, 196])